# Generated by Django 5.0 on 2024-02-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeroaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_in_grams', models.IntegerField(default=200)),
                ('price', models.IntegerField()),
                ('tags', models.ManyToManyField(to='coffeeroaster.tag')),
            ],
        ),
    ]
